apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    build.appstudio.openshift.io/application: test-app-mlpl
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/component: test-component--nmlf
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: test-component--nmlf
  namespace: e2e-test-pipelines-etey
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: test-component--nmlf
status:
  configuration:
    generatedName: ""
